# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'ZSQRCodeReaderDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'TZImagePickerController'
  # Pods for ZSQRCodeReaderDemo

end
